# Generated by Django 5.1.6 on 2025-04-02 08:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
