# Generated by Django 5.1.6 on 2025-03-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(default='doctor_images/default.jpg', upload_to='doctor_images/'),
        ),
    ]
