# Generated by Django 5.1.6 on 2025-03-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(upload_to='doctor_images/'),
        ),
    ]
