# Generated by Django 5.1.6 on 2025-03-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_payment_payment_intent_id_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.doctorschedule'),
        ),
    ]
